# P&L (minimum viable)
Revenue: {}
COGS: {}
Gross Profit: {}
Sales & Marketing: {}
Research & Development: {}
General & Administrative: {}
Depreciation & Amortization: {}
Share-Based Compensation: {}
Operating Income (EBIT): {}
Interest Expense: {}
Interest Income: {}
Other Income (Expense): {}
Income Before Taxes: {}
Income Tax Expense: {}
Net Income: {}
